# Generated by Django 4.1.7 on 2023-02-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_alter_share_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='share',
            old_name='date',
            new_name='timestamp',
        ),
    ]
